#!/bin/bash

if [ -f /etc/tunneldigger/config ]; then
  . /etc/tunneldigger/config
fi

session_up()
{
  local interface="$1"

  if [ -n "${TUNNELDIGGER_BRIDGE}" ]; then
    ip link add dev td0 type bridge 2>/dev/null && {
      # Bridge did not exist before, initialize it
      ip link set dev td0 up
      ip link set dev ${TUNNELDIGGER_BRIDGE} master td0
    }

    ip link set dev ${interface} master td0
  fi

  ip link set dev ${interface} up
}

session_down()
{
  local interface="$1"

  if [ -n "${TUNNELDIGGER_BRIDGE}" ]; then
    ip link set dev ${interface} nomaster
  fi
}

HOOK="$1"
INTERFACE="$2"

case "${HOOK}" in
  session.up) session_up $INTERFACE ;;
  session.down) session_down $INTERFACE ;;
esac

